/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 clothes.gltf --transform
Author: Androkumura (https://sketchfab.com/Androkumura)
License: CC-BY-NC-ND-4.0 (http://creativecommons.org/licenses/by-nc-nd/4.0/)
Source: https://sketchfab.com/3d-models/casual-clothes-3d76c9f61c9140f2ab61c601af3f5e71
Title: Casual Clothes
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/clothes-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.Pocket_FRONT_7674} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.Material7471} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.Tshirt_FRONT_7678} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.Waist_Belt_FRONT_7670} />
      </group>
    </group>
  )
}

useGLTF.preload('/clothes-transformed.glb')
