/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 shoes.gltf --transform
Author: MartinMaH (https://sketchfab.com/MartinMaH)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/red-high-heel-shoes-33805e7cc2804ea4bab58a5147b4badc
Title: Red High-Heel Shoes
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/shoes-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.defaultMaterial.geometry} material={materials.Shoes} />
          <mesh geometry={nodes.defaultMaterial_1.geometry} material={materials.Shoes} />
          <mesh geometry={nodes.defaultMaterial_2.geometry} material={materials.Shoes} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/shoes-transformed.glb')
